export const APP_ROUTES = {
  root: "/",
  login: "/login",
  dashboard: "/dashboard",
  manageUsers: "/manage-users",
  adsManagement: "/ads-management",
  adRequests: "/ads-management/ad-requests",
  reportedAds: "/ads-management/reported-ads",
  videoManagement: "/video-management",
  rdi: "/rdi",
  financials: "/financials",
  advertisersPayment: "/financials/advertisers-payment",
  withdrawals: "/financials/withdrawals",
  support: "/support",
  manageAdmins: "/manage-admins",
  settings: "/settings",
} as const
