import { Building2, Check, Clock, Droplets, HardHat, Settings, Shield, Wrench } from "lucide-react"
import { useState } from "react"
import type { RdiContentBlock } from "@/features/rdi/types"
import { RdiAction, RdiHeading, RdiImage, RdiLink, RdiSection } from "@/features/rdi/components/RdiPreviewPrimitives"
import { useRdiPreview } from "@/features/rdi/components/RdiPreviewContext"

function ConstructionProcess({ block }: { block: RdiContentBlock }) {
  const [active, setActive] = useState(0)
  return <RdiSection block={block} className="bg-gradient-to-b from-[#F8FAFC] to-white py-20"><div className="rdi-container px-4"><RdiHeading block={block} /><div className="mx-auto mb-16 flex max-w-3xl gap-4 px-4">{block.items?.map((item, index) => <button type="button" key={item.id} aria-label={`View process step ${index + 1}`} aria-pressed={index === active} onClick={() => setActive(index)} className="relative h-10 flex-1"><span className={`block h-2 rounded-full ${index <= active ? "bg-orange-500" : "bg-slate-200"}`} /><span className={`absolute left-1/2 top-1/2 flex size-8 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full font-bold ${index <= active ? "scale-125 bg-orange-500 text-white" : "bg-slate-200 text-slate-500"}`}>{index + 1}</span></button>)}</div><div className="mx-auto grid max-w-5xl gap-8 px-4 sm:px-6 md:grid-cols-2">{block.items?.map((item, index) => <button key={item.id} type="button" onClick={() => setActive(index)} aria-pressed={index === active} className={`relative rounded-2xl bg-white p-8 text-left shadow-adbox-medium transition-shadow hover:shadow-adbox-large ${index === active ? "ring-4 ring-orange-500" : ""}`}><span className="absolute -left-3 -top-4 flex size-14 items-center justify-center rounded-xl bg-gradient-to-br from-orange-500 to-orange-400 text-2xl font-bold text-white sm:-left-5">{item.eyebrow || String(index + 1).padStart(2, "0")}</span><span className="mb-4 mt-4 block text-2xl font-semibold text-slate-800">{item.title}</span><span className="leading-relaxed text-slate-500">{item.description}</span></button>)}</div></div></RdiSection>
}

function ConstructionSupplies({ block }: { block: RdiContentBlock }) {
  const fittings = block.items?.[0]
  const machine = block.items?.[1]
  return <RdiSection block={block} id="supplies" className="scroll-mt-28 bg-[#F8FAFC] py-16 sm:py-20"><div className="rdi-container px-4"><RdiHeading block={block} />
    {fittings ? <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-adbox-medium"><div className="grid lg:grid-cols-2"><div className="flex flex-col justify-center p-6 sm:p-10"><RdiImage media={fittings.media} contain /><RdiLink href="https://www.richdadinvestments.org/construction/hdpe-fittings-guide.jpg" target="_blank" rel="noreferrer" className="mt-6 text-center text-sm font-semibold text-[#C2410C]">View the full fittings guide →</RdiLink></div><div className="border-t border-slate-100 p-6 sm:p-10 lg:border-l lg:border-t-0"><p className="mb-3 text-sm font-bold uppercase tracking-[0.15em] text-[#C2410C]">Pipework essentials</p><h3 className="text-2xl font-bold text-[#1E293B] sm:text-3xl">{fittings.title}</h3><p className="mt-4 leading-relaxed text-[#64748B]">{fittings.description}</p><dl className="my-6 grid grid-cols-2 gap-3">{[["Size range", "DN 40 – DN 800"], ["Pressure range", "PN 10 – PN 25"]].map(([label, value]) => <div key={label} className="rounded-xl bg-orange-50 p-4"><dt className="text-xs font-semibold uppercase tracking-wider text-[#9A3412]">{label}</dt><dd className="mt-1 text-lg font-bold text-[#1E293B]">{value}</dd></div>)}</dl><ul className="grid gap-x-4 gap-y-3 sm:grid-cols-2">{fittings.features?.map((feature, index) => <li key={index} className="flex items-start gap-2 text-sm text-slate-600"><Check className="mt-0.5 size-4 shrink-0 text-[#C2410C]" />{feature}</li>)}</ul><RdiAction label={fittings.buttonLabel} href={fittings.buttonHref} className="mt-8" /></div></div></article> : null}
    {machine ? <article className="mt-8 overflow-hidden rounded-3xl bg-gradient-to-br from-[#1E293B] to-[#334155] shadow-adbox-medium"><div className="grid items-center lg:grid-cols-2"><div className="p-6 sm:p-10 lg:p-12"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-orange-300/30 bg-orange-400/10 px-4 py-2 text-sm font-semibold text-orange-200"><Wrench className="size-4" />Available for sale & rental</div><h3 className="text-3xl font-bold text-white sm:text-4xl">{machine.title}</h3><p className="mt-5 text-lg leading-relaxed text-slate-300">{machine.description}</p><p className="mt-6 text-2xl font-bold text-[#FB923C]">DN 50 – DN 800</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><RdiAction label={machine.buttonLabel} href={machine.buttonHref} /><RdiAction label="Discuss a Rental" href="tel:+233244389842" secondary /></div></div><div className="grid grid-cols-2 gap-3 p-6 pt-0 sm:p-8 lg:pl-0 lg:pt-8"><RdiImage media={machine.media} className="col-span-2 aspect-[4/3] rounded-2xl" /><img src="https://www.richdadinvestments.org/construction/butt-fusion-machine.jpg" alt="Butt-fusion welding machine and control equipment" className="aspect-[3/2] w-full rounded-xl bg-white object-contain p-2" /><img src="https://www.richdadinvestments.org/construction/butt-fusion-workshop.jpg" alt="Butt-fusion machine joining a pipe in a workshop" className="aspect-[3/2] w-full rounded-xl object-cover" /></div></div></article> : null}
  </div></RdiSection>
}

export function RdiLiveConstructionBlock({ block }: { block: RdiContentBlock }) {
  const { settings } = useRdiPreview()
  if (block.id === "construction-process") return <ConstructionProcess block={block} />
  if (block.id === "construction-supplies") return <ConstructionSupplies block={block} />
  if (block.type === "hero") return <RdiSection block={block} className="overflow-hidden bg-gradient-to-br from-[#1E293B] via-[#334155] to-[#1E293B] py-24 md:py-32"><div className="pointer-events-none absolute inset-0 opacity-10"><div className="absolute left-10 top-20 size-72 rounded-full bg-[#F97316] blur-3xl" /></div><div className="rdi-container relative px-4 text-center"><h1 className="mb-6 text-4xl font-bold leading-tight text-white sm:text-5xl md:text-6xl">{block.title}</h1><p className="mx-auto mb-8 max-w-3xl text-xl leading-relaxed text-[#CBD5E1] md:text-2xl">{block.description}</p><div className="flex flex-col justify-center gap-3 sm:flex-row"><RdiAction label={block.buttonLabel} href={block.buttonHref} /><RdiAction label={block.secondaryButtonLabel} href={block.secondaryButtonHref} secondary className="[&_svg]:hidden" /></div></div></RdiSection>
  if (block.id === "construction-stats") return <RdiSection block={block} className="bg-white py-12 sm:py-16"><div className="rdi-container grid grid-cols-2 gap-6 px-4 md:grid-cols-4 md:gap-8">{block.items?.map((item, index) => { const Icon = [Building2, Droplets, Settings, Wrench][index % 4]; return <div key={item.id} className="group text-center"><div className="mb-4 inline-flex size-16 items-center justify-center rounded-2xl bg-orange-50 text-[#C2410C]"><Icon className="size-8" /></div><h2 className="mb-2 text-lg font-bold text-[#1E293B] sm:text-xl">{item.title}</h2><p className="text-sm leading-relaxed text-[#64748B]">{item.description}</p></div> })}</div></RdiSection>
  if (block.type === "split") return <RdiSection block={block} className="bg-[#F8FAFC] py-16 sm:py-20"><div className="rdi-container grid items-center gap-10 px-4 lg:grid-cols-2 lg:gap-16"><div className="relative"><RdiImage media={block.media} className="aspect-[4/3] rounded-2xl shadow-adbox-large" /><div className="absolute bottom-5 left-5 right-5 rounded-xl border border-white/15 bg-[#1E293B]/95 p-5 text-white shadow-adbox-medium sm:left-8 sm:right-auto"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#FB923C]">Our commitment</p><p className="mt-2 text-xl font-semibold">Service by excellence</p></div></div><div><p className="mb-3 text-sm font-bold uppercase tracking-[0.2em] text-[#C2410C]">{block.eyebrow}</p><h2 className="text-3xl font-bold text-[#1E293B] sm:text-4xl">{block.title}</h2><p className="mt-5 whitespace-pre-line text-lg leading-relaxed text-[#64748B]">{block.description}</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{block.items?.map(item => <div key={item.id} className="rounded-xl border border-orange-100 bg-white p-5"><h3 className="font-semibold text-[#1E293B]">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-[#64748B]">{item.description}</p></div>)}</div></div></div></RdiSection>
  if (block.id === "construction-solar-cta") return <RdiSection block={block} className="bg-white px-4 py-16"><div className="rdi-container"><div className="mx-auto flex max-w-5xl flex-col items-center justify-between gap-8 rounded-2xl border border-emerald-100 bg-gradient-to-r from-amber-50 to-emerald-50 p-6 shadow-adbox-medium sm:p-8 md:flex-row"><div className="text-center md:text-left"><h2 className="mb-2 text-2xl font-bold text-slate-900 md:text-3xl">{block.title}</h2><p className="text-lg text-slate-500">{block.description}</p></div><RdiAction label={block.buttonLabel} href={block.buttonHref} className="shrink-0 bg-amber-400 text-slate-900 hover:bg-amber-300" /></div></div></RdiSection>
  if (block.type === "cta") return <RdiSection block={block} className="bg-[#F8FAFC] py-20"><div className="rdi-container px-4"><div className="grid items-center gap-8 rounded-3xl bg-gradient-to-r from-[#1E293B] to-[#334155] p-6 sm:p-10 md:p-16 lg:grid-cols-2"><div className="text-center lg:text-left"><HardHat className="mx-auto mb-6 size-16 text-orange-500 lg:mx-0" /><h2 className="mb-4 text-3xl font-bold text-white md:text-4xl">{block.title}</h2><p className="mb-8 text-lg text-slate-300">{block.description}</p><RdiAction label={block.buttonLabel} href={block.buttonHref} /><div className="mt-6 space-y-3 text-sm text-slate-300"><RdiLink href="tel:+233244389842" className="block">+233 (0) 24 438 9842</RdiLink><RdiLink href="tel:+233262677977" className="block">+233 (0) 26 267 7977</RdiLink><p>{settings.contactAddress.replace("\n", ", ")}</p></div></div><RdiImage media={block.media} className="hidden rounded-2xl shadow-adbox-large lg:block" /></div></div></RdiSection>
  const gallery = block.id === "construction-project-gallery"
  if (gallery) return <RdiSection block={block} className="bg-white py-16 sm:py-20"><div className="rdi-container px-4"><RdiHeading block={block} /><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{block.items?.map(item => <figure key={item.id} className="group relative h-80 overflow-hidden rounded-2xl bg-slate-100"><RdiImage media={item.media} className="h-full w-full transition-transform duration-500 group-hover:scale-105" /><figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#0F172A] via-[#0F172A]/85 to-transparent px-6 pb-6 pt-20"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-orange-200">{item.description}</p><h3 className="text-xl font-semibold text-white">{item.title}</h3></figcaption></figure>)}</div></div></RdiSection>
  const why = block.id === "construction-why"
  return <RdiSection block={block} id={block.id === "construction-services" ? "services" : block.id} className="scroll-mt-28 bg-white py-16 sm:py-20"><div className="rdi-container px-4"><RdiHeading block={block} /><div className={`grid grid-cols-1 gap-8 md:grid-cols-2 ${why ? "lg:grid-cols-4" : "lg:grid-cols-3"}`}>{block.items?.filter(item => item.visible !== false).map((item, index) => { const Icon = [Shield, Clock, HardHat, Wrench][index % 4]; return <article key={item.id} className="group flex h-full flex-col overflow-hidden rounded-2xl bg-white shadow-adbox-medium transition-all hover:-translate-y-2 hover:shadow-adbox-large"><RdiImage media={item.media} className={`${gallery ? "aspect-[4/3]" : "h-64"} ${item.media ? "" : "hidden"} [&_img]:transition-transform group-hover:[&_img]:scale-105`} /><div className="flex flex-1 flex-col p-8">{why ? <div className="mb-4 inline-flex size-16 items-center justify-center rounded-2xl bg-[#F97316]/10"><Icon className="size-8 text-[#F97316]" /></div> : null}<h3 className="mb-3 text-xl font-semibold text-[#1E293B]">{item.title}</h3><p className="leading-relaxed text-[#64748B]">{item.description}</p>{item.buttonLabel ? <RdiAction label={item.buttonLabel} href={item.buttonHref} className="mt-6 justify-start bg-transparent p-0 text-[#C2410C] hover:bg-transparent" /> : null}</div></article> })}</div></div></RdiSection>
}
