import type { RdiSiteContent } from "@/features/rdi/types"

export const RDI_STORAGE_KEY = "adbox-rdi-cms-content-v3"

export const initialRdiSiteContent: RdiSiteContent = {
  version: 3,
  settings: {
    siteName: "RichDad Investments",
    footerDescription:
      "Building spaces, shaping stories, and powering progress through three specialized divisions.",
    footerQuickLinksHeading: "Our Divisions",
    footerQuickLinks: [
      "Construction",
      "Media Production",
      "Solar Technology",
      "Request a Consultation",
    ],
    footerServicesHeading: "Company",
    footerServices: ["Home", "About Us", "Contact"],
    footerContactHeading: "Contact",
    contactAddress: "45 Independence Avenue\nNorth Ridge, Accra, Ghana",
    contactPhone: "+233 (0) 30 123 4567",
    contactEmail: "info@richdadinvestments.com",
    legalLinks: [],
    copyright: "© 2026 RichDad Investments. All rights reserved.",
  },
  pages: [
    {
      id: "home",
      name: "Home page",
      navigationLabel: "Home",
      slug: "/",
      status: "Published",
      blocks: [
        {
          id: "home-hero",
          type: "hero",
          name: "Hero banner",
          visible: true,
          eyebrow: "Three Divisions. One Vision. Endless Possibilities.",
          title: "Welcome to RichDad Investments",
          description: "Choose your path to discover how we can transform your project",
        },
        {
          id: "home-divisions",
          type: "cards",
          name: "Business divisions",
          visible: true,
          eyebrow: "",
          title: "Business divisions",
          description: "Choose the division that best fits your project.",
          items: [
            {
              id: "home-construction",
              title: "Construction",
              description:
                "Building tomorrow's infrastructure today. From commercial complexes to residential dreams, we bring structural excellence to every project.",
              features: [
                "Commercial & Industrial Buildings",
                "Residential Development",
                "Renovations & Remodeling",
                "Project Management",
              ],
              buttonLabel: "Explore Construction",
              buttonHref: "/construction",
              media: {
                type: "image",
                url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&h=800",
                alt: "Construction professionals working on a building project",
              },
            },
            {
              id: "home-media",
              title: "Media",
              description:
                "Crafting compelling stories through digital innovation. From concept to creation, we bring your brand's vision to life.",
              features: [
                "Video Production & Photography",
                "Digital Marketing Solutions",
                "Brand Development",
                "Content Strategy",
              ],
              buttonLabel: "Explore Media",
              buttonHref: "/media",
              media: {
                type: "image",
                url: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&h=800",
                alt: "Media Production",
              },
            },
            {
              id: "home-solar",
              title: "Solar Technology",
              description:
                "Powering homes and businesses with reliable solar panel technology. We deliver efficient, sustainable energy systems designed for long-term savings.",
              features: [
                "Solar Panel Installation",
                "Energy Storage Solutions",
                "System Design & Consultation",
                "Maintenance & Performance Monitoring",
              ],
              buttonLabel: "Explore Solar Technology",
              buttonHref: "/solar",
              media: {
                type: "image",
                url: "https://images.unsplash.com/photo-1509391366360-2e959784a276?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&h=800",
                alt: "Solar panels generating clean energy",
              },
            },
          ],
        },
        {
          id: "home-cta",
          type: "cta",
          name: "Guidance call to action",
          visible: true,
          eyebrow: "",
          title: "Not sure which division you need?",
          description: "",
          buttonLabel: "Contact Us for Guidance",
          buttonHref: "/contact",
        },
      ],
    },
    {
      id: "about",
      name: "About page",
      navigationLabel: "About",
      slug: "/about",
      status: "Published",
      blocks: [
        {
          id: "about-hero",
          type: "hero",
          name: "About hero",
          visible: true,
          eyebrow: "About RichDad Investments",
          title: "Three disciplines. One connected vision.",
          description:
            "We build enduring spaces, create meaningful stories, and deliver cleaner energy systems that help people and businesses move forward.",
        },
        {
          id: "about-divisions",
          type: "cards",
          name: "Division overview",
          visible: true,
          eyebrow: "",
          title: "Explore our divisions",
          description: "Specialized teams, connected by one standard of thoughtful delivery.",
          items: [
            {
              id: "about-construction",
              eyebrow: "Building the future, one project at a time",
              title: "Construction Division",
              description:
                "Our construction division brings together planning, craftsmanship, and project management to deliver commercial and residential spaces that perform beautifully.",
              features: [
                "Commercial and residential construction",
                "Renovation and remodelling",
                "Design-build coordination",
                "Project management",
                "Our promise — From the first brief to final handover, we keep quality, safety, clear communication, and responsible delivery at the centre of the project.",
              ],
              buttonLabel: "Explore Construction",
              buttonHref: "/construction",
            },
            {
              id: "about-media",
              title: "Media",
              description: "Creative production and communication shaped around meaningful stories.",
              buttonLabel: "Explore Media",
              buttonHref: "/media",
            },
            {
              id: "about-solar",
              title: "Solar Technology",
              description: "Practical renewable energy systems for homes and businesses.",
              buttonLabel: "Explore Solar Technology",
              buttonHref: "/solar",
            },
          ],
        },
        {
          id: "about-story",
          type: "split",
          name: "Our story",
          visible: true,
          eyebrow: "Our story",
          title: "Expertise that grows with the needs of our clients",
          description:
            "RichDad Investments began with a vision to combine physical construction expertise with the creative power of digital media. That connected approach gave clients fewer handoffs and a more consistent path from idea to delivery.\n\nAs reliable, sustainable power became increasingly important to the homes and businesses we serve, Solar Technology became our third specialized division. It extends the same practical mindset into energy assessment, solar installation, storage, monitoring, and support.\n\nToday, our teams can work independently or together—building a facility, communicating its story, and helping power its future.",
          media: {
            type: "image",
            url: "https://www.richdadinvestments.org/36.jpg",
            alt: "The RichDad Investments team collaborating",
          },
        },
        {
          id: "about-values",
          type: "cards",
          name: "What sets us apart",
          visible: true,
          eyebrow: "",
          title: "What sets us apart",
          description:
            "Connected expertise creates more options and a clearer experience for every client.",
          items: [
            {
              id: "about-collaboration",
              title: "Collaborative teams",
              description:
                "Construction, media, and solar specialists can coordinate around one brief and one shared outcome.",
            },
            {
              id: "about-innovation",
              title: "Practical innovation",
              description:
                "We choose technology and creative approaches for their real-world value, not novelty alone.",
            },
            {
              id: "about-delivery",
              title: "Purposeful delivery",
              description:
                "Every solution is shaped around your goals, constraints, users, and long-term success.",
            },
          ],
        },
        {
          id: "about-cta",
          type: "cta",
          name: "About call to action",
          visible: true,
          eyebrow: "",
          title: "Talk to Our Team",
          description: "",
          buttonLabel: "Talk to Our Team",
          buttonHref: "/contact",
        },
      ],
    },
    {
      id: "construction",
      name: "Construction page",
      navigationLabel: "Construction",
      slug: "/construction",
      status: "Published",
      blocks: [
        {
          id: "construction-hero",
          type: "hero",
          name: "Construction hero",
          visible: true,
          eyebrow: "",
          title: "Construction Services",
          description:
            "Building excellence with precision, quality, and innovation. From concept to completion, we deliver exceptional construction solutions.",
        },
        {
          id: "construction-stats",
          type: "stats",
          name: "Construction numbers",
          visible: true,
          eyebrow: "",
          title: "Construction numbers",
          description: "",
          items: [
            { id: "construction-projects", title: "250+", description: "Projects Completed" },
            { id: "construction-clients", title: "500+", description: "Happy Clients" },
            { id: "construction-team", title: "50+", description: "Expert Workers" },
            { id: "construction-success", title: "98%", description: "Success Rate" },
          ],
        },
        {
          id: "construction-why",
          type: "cards",
          name: "Why choose us",
          visible: true,
          eyebrow: "",
          title: "Why Choose Us",
          description:
            "We combine decades of experience with cutting-edge techniques to deliver superior results",
          items: [
            { id: "construction-quality", title: "Quality First", description: "Uncompromising standards in every project we undertake" },
            { id: "construction-delivery", title: "On-Time Delivery", description: "We respect deadlines and deliver projects as promised" },
            { id: "construction-experts", title: "Expert Team", description: "Skilled professionals with years of industry experience" },
            { id: "construction-full-service", title: "Full Service", description: "Complete solutions from design to final handover" },
          ],
        },
        {
          id: "construction-services",
          type: "cards",
          name: "Construction services",
          visible: true,
          eyebrow: "",
          title: "Our Services",
          description: "Comprehensive construction solutions tailored to your needs",
          items: [
            {
              id: "construction-commercial",
              title: "Commercial Construction",
              description: "Complete construction services for office buildings, retail spaces, warehouses, and other commercial properties with focus on functionality and efficiency.",
              buttonLabel: "Learn More",
              media: { type: "image", url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80", alt: "Commercial Construction" },
            },
            {
              id: "construction-residential",
              title: "Residential Construction",
              description: "From single-family homes to multi-unit developments, we create living spaces that combine comfort, style, and durability.",
              buttonLabel: "Learn More",
              media: { type: "image", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", alt: "Residential Construction" },
            },
            {
              id: "construction-renovation",
              title: "Renovation & Remodeling",
              description: "Transform existing spaces with our expert renovation services, whether updating a single room or an entire building.",
              buttonLabel: "Learn More",
              media: { type: "image", url: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800&q=80", alt: "Renovation & Remodeling" },
            },
            {
              id: "construction-management",
              title: "Project Management",
              description: "End-to-end project management ensuring your construction stays on schedule, within budget, and meets all quality standards.",
              buttonLabel: "Learn More",
              media: { type: "image", url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80", alt: "Project Management" },
            },
            {
              id: "construction-design-build",
              title: "Design-Build Services",
              description: "Integrated design and construction services for a seamless experience from concept through completion.",
              buttonLabel: "Learn More",
              media: { type: "image", url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80", alt: "Design-Build Services" },
            },
            {
              id: "construction-green",
              title: "Green Building",
              description: "Sustainable construction practices using eco-friendly materials and energy-efficient designs for environmentally responsible buildings.",
              buttonLabel: "Learn More",
              media: { type: "image", url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80", alt: "Green Building" },
            },
          ],
        },
        {
          id: "construction-process",
          type: "cards",
          name: "Our process",
          visible: true,
          eyebrow: "",
          title: "Our Process",
          description: "A streamlined approach that ensures your project runs smoothly from start to finish",
          items: [
            { id: "construction-process-1", eyebrow: "01", title: "Initial Consultation", description: "We meet with you to understand your vision, requirements, budget, and timeline. Our experts provide initial guidance and feasibility assessment." },
            { id: "construction-process-2", eyebrow: "02", title: "Design & Planning", description: "Our team creates detailed plans, blueprints, and schedules. We handle all permits and ensure compliance with regulations." },
            { id: "construction-process-3", eyebrow: "03", title: "Construction Phase", description: "Expert execution with regular progress updates. Quality control at every stage ensures the highest standards are maintained." },
            { id: "construction-process-4", eyebrow: "04", title: "Final Delivery", description: "Thorough inspection and walkthrough. We ensure complete satisfaction and provide warranty support for your peace of mind." },
          ],
        },
        {
          id: "construction-project-gallery",
          type: "cards",
          name: "Recent projects",
          visible: true,
          eyebrow: "",
          title: "Our Recent Projects",
          description: "Take a look at some of our completed construction projects",
          items: [
            { id: "construction-project-1", title: "Modern Office Complex", description: "Downtown Business District", media: { type: "image", url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80", alt: "Modern office complex construction project" } },
            { id: "construction-project-2", title: "Luxury Residence", description: "Private Estate", media: { type: "image", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", alt: "Completed luxury residential construction project" } },
            { id: "construction-project-3", title: "Architectural Design", description: "Commercial Building", media: { type: "image", url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80", alt: "Architectural design and construction planning" } },
          ],
        },
        {
          id: "construction-cta",
          type: "cta",
          name: "Construction call to action",
          visible: true,
          eyebrow: "",
          title: "Let's Build Something Amazing Together",
          description: "Ready to start your construction project? Get in touch for a free consultation and quote.",
          buttonLabel: "Get Your Free Quote",
          buttonHref: "/contact",
        },
        {
          id: "construction-solar-cta",
          type: "cta",
          name: "Solar Technology callout",
          visible: true,
          eyebrow: "",
          title: "Planning an energy-ready property?",
          description: "Explore how our Solar Technology division can complement your construction project.",
          buttonLabel: "Explore Solar Technology",
          buttonHref: "/solar",
        },
      ],
    },
    {
      id: "media",
      name: "Media page",
      navigationLabel: "Media",
      slug: "/media",
      status: "Published",
      blocks: [
        {
          id: "media-hero",
          type: "hero",
          name: "Media hero",
          visible: true,
          eyebrow: "Award-Winning Media Production",
          title: "Stories That Move People",
          description: "We create stunning visual content that captivates audiences and drives results",
          media: { type: "image", url: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?w=1600", alt: "Creative media production workspace" },
        },
        {
          id: "media-stats",
          type: "stats",
          name: "Media numbers",
          visible: true,
          eyebrow: "",
          title: "Media impact",
          description: "",
          items: [
            { id: "media-awards", title: "24+", description: "Industry Awards" },
            { id: "media-clients", title: "150+", description: "Happy Clients" },
            { id: "media-projects", title: "500+", description: "Projects Delivered" },
            { id: "media-views", title: "50M+", description: "Total Views" },
          ],
        },
        {
          id: "media-work",
          type: "cards",
          name: "Featured work",
          visible: true,
          eyebrow: "",
          title: "Featured Work",
          description: "Explore our latest creative projects",
          items: [
            { id: "media-tech", eyebrow: "4K Video · Motion Graphics", title: "Tech Innovation Campaign", description: "A cutting-edge commercial campaign that increased brand awareness by 200%", features: ["TechCorp", "2024"], media: { type: "image", url: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?w=800", alt: "Tech Innovation Campaign" } },
            { id: "media-documentary", eyebrow: "Documentary · Cinematography", title: "Urban Stories Documentary", description: "Award-winning documentary series exploring urban culture", features: ["City Arts", "2024"], media: { type: "image", url: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800", alt: "Urban Stories Documentary" } },
            { id: "media-ecolife", eyebrow: "Logo Design · Brand Strategy", title: "EcoLife Brand Identity", description: "Complete brand redesign for sustainable lifestyle company", features: ["EcoLife", "2024"], media: { type: "image", url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800", alt: "EcoLife Brand Identity" } },
            { id: "media-animation", eyebrow: "3D Animation · VFX", title: "Animated Product Launch", description: "3D animation for innovative product reveal", features: ["StartupX", "2024"], media: { type: "image", url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800", alt: "Animated Product Launch" } },
            { id: "media-fashion", eyebrow: "Event Coverage · Quick Cuts", title: "Fashion Week Recap", description: "High-energy recap of international fashion week", features: ["StyleMag", "2024"], media: { type: "image", url: "https://images.unsplash.com/photo-1445510861639-5651173bc5d5?w=800", alt: "Fashion Week Recap" } },
            { id: "media-restaurant", eyebrow: "Menu Design · Photography", title: "Restaurant Rebranding", description: "Full visual identity for upscale restaurant chain", features: ["Savory Kitchen", "2024"], media: { type: "image", url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800", alt: "Restaurant Rebranding" } },
          ],
        },
        {
          id: "media-cta",
          type: "cta",
          name: "Media call to action",
          visible: true,
          eyebrow: "",
          title: "Let's Create Something Amazing",
          description: "Ready to bring your vision to life? Get in touch with our creative team today.",
          buttonLabel: "Get Started",
          buttonHref: "/contact",
        },
      ],
    },
    {
      id: "solar",
      name: "Solar Technology page",
      navigationLabel: "Solar Technology",
      slug: "/solar",
      status: "Published",
      blocks: [
        {
          id: "solar-hero",
          type: "hero",
          name: "Solar hero",
          visible: true,
          eyebrow: "Clean energy designed around you",
          title: "Smarter solar power for a brighter future",
          description: "From site assessment to installation and support, we build solar panel systems that give homes and businesses practical, dependable access to renewable energy.",
          buttonLabel: "Request a Solar Consultation",
          buttonHref: "/contact",
          secondaryButtonLabel: "Explore Solutions",
          secondaryButtonHref: "#solutions",
          media: { type: "image", url: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1800&q=85", alt: "Solar panels capturing sunlight" },
        },
        {
          id: "solar-benefits",
          type: "cards",
          name: "Solar benefits",
          visible: true,
          eyebrow: "",
          title: "Solar benefits",
          description: "",
          items: [
            { id: "solar-independence", title: "Energy independence", description: "Generate power at your property and reduce reliance on the grid." },
            { id: "solar-cleaner", title: "Cleaner operations", description: "Use renewable energy to reduce the environmental impact of daily power needs." },
            { id: "solar-reliable", title: "Built for reliability", description: "Thoughtful design, quality installation, and support protect long-term performance." },
          ],
        },
        {
          id: "solar-solutions",
          type: "cards",
          name: "Solar solutions",
          visible: true,
          eyebrow: "Solar solutions",
          title: "Technology for every stage of your energy journey",
          description: "Flexible services for new systems, energy upgrades, and ongoing care—planned around how your property actually uses power.",
          items: [
            { id: "solar-residential", title: "Residential Solar", description: "Right-sized rooftop systems that help households reduce grid dependence and manage everyday energy costs." },
            { id: "solar-commercial", title: "Commercial Solar", description: "Scalable solar solutions for offices, retail spaces, schools, facilities, and industrial operations." },
            { id: "solar-storage", title: "Battery Storage", description: "Reliable energy storage designed to keep essential equipment powered when sunlight or grid power is unavailable." },
            { id: "solar-assessment", title: "Energy Assessment", description: "Site surveys and consumption reviews that shape a practical system around your property, usage, and goals." },
            { id: "solar-monitoring", title: "Smart Monitoring", description: "Clear performance monitoring so you can understand production, consumption, and overall system health." },
            { id: "solar-care", title: "Care & Maintenance", description: "Inspection, cleaning, diagnostics, and support that protect system efficiency over the long term." },
          ],
        },
        {
          id: "solar-process",
          type: "cards",
          name: "Solar process",
          visible: true,
          eyebrow: "Our process",
          title: "A clear path from energy need to working system",
          description: "Practical renewable energy, professionally delivered.",
          items: [
            { id: "solar-process-1", eyebrow: "01", title: "Consultation", description: "We learn about your energy needs, property, and priorities." },
            { id: "solar-process-2", eyebrow: "02", title: "Site & System Design", description: "Our team assesses the site and develops a tailored solar solution." },
            { id: "solar-process-3", eyebrow: "03", title: "Professional Installation", description: "The system is installed carefully, tested, and prepared for handover." },
            { id: "solar-process-4", eyebrow: "04", title: "Monitoring & Support", description: "We help you understand performance and keep the system operating well." },
          ],
        },
        {
          id: "solar-cta",
          type: "cta",
          name: "Solar call to action",
          visible: true,
          eyebrow: "",
          title: "Ready to put the sun to work?",
          description: "Tell us about your property and energy needs. Our solar team will help you understand the right next step.",
          buttonLabel: "Start Your Solar Project",
          buttonHref: "/contact",
        },
      ],
    },
    {
      id: "contact",
      name: "Contact page",
      navigationLabel: "Contact",
      slug: "/contact",
      status: "Published",
      blocks: [
        {
          id: "contact-hero",
          type: "hero",
          name: "Contact hero",
          visible: true,
          eyebrow: "Start a conversation",
          title: "Let's build, create, and power what's next",
          description: "Tell us whether you need construction, media, solar technology, or a connected solution. We'll help you find the right path.",
        },
        {
          id: "contact-form",
          type: "cards",
          name: "Project enquiry form",
          visible: true,
          eyebrow: "",
          title: "Tell us about your project",
          description: "Share a few details and select the division that best matches your needs.",
          items: [
            { id: "contact-first-name", title: "First Name", description: "Your first name" },
            { id: "contact-last-name", title: "Last Name", description: "Your last name" },
            { id: "contact-email-field", title: "Email Address", description: "your.email@example.com" },
            { id: "contact-phone-field", title: "Phone Number", description: "(123) 456-7890" },
            { id: "contact-service", title: "Service Interested In", description: "Select a service", features: ["Construction Services", "Media Services", "Solar Technology Services", "Multi-Division Project", "Other"] },
            { id: "contact-message", title: "Message", description: "Tell us about your project" },
          ],
          buttonLabel: "Send Message",
        },
        {
          id: "contact-details",
          type: "cards",
          name: "Contact information",
          visible: true,
          eyebrow: "",
          title: "Contact information",
          description: "",
          items: [
            { id: "contact-visit", eyebrow: "Visit us", title: "45 Independence Avenue", description: "North Ridge, Accra, Ghana" },
            { id: "contact-call", eyebrow: "Call us", title: "+233 (0) 30 123 4567", description: "" },
            { id: "contact-email", eyebrow: "Email us", title: "info@richdadinvestments.com", description: "" },
            { id: "contact-hours", eyebrow: "Office hours", title: "Monday–Friday: 8:00–17:00", description: "" },
          ],
        },
        {
          id: "contact-solar-note",
          type: "cta",
          name: "Solar project note",
          visible: true,
          eyebrow: "",
          title: "Planning a solar project?",
          description: "Include your location, typical power needs, and property type in the message so our solar team can prepare for the first conversation.",
        },
        {
          id: "contact-teams",
          type: "cards",
          name: "Division contacts",
          visible: true,
          eyebrow: "",
          title: "Speak with the right team",
          description: "Each division has dedicated specialists ready to understand your project.",
          items: [
            { id: "contact-construction-team", title: "Construction", description: "Building, renovation, and project enquiries", features: ["construction@richdadinvestments.com"] },
            { id: "contact-media-team", title: "Media", description: "Production, branding, and campaign enquiries", features: ["media@richdadinvestments.com"] },
            { id: "contact-solar-team", title: "Solar Technology", description: "Solar systems, storage, and support enquiries", features: ["solar@richdadinvestments.com"] },
          ],
        },
        {
          id: "contact-faq",
          type: "cards",
          name: "Frequently asked questions",
          visible: true,
          eyebrow: "",
          title: "Frequently asked questions",
          description: "Helpful details before we begin.",
          items: [
            { id: "contact-faq-1", title: "Which areas do you serve?", description: "We are based in Accra and primarily serve the Greater Accra Region, with project availability across Ghana depending on scope and requirements." },
            { id: "contact-faq-2", title: "Do you offer an initial consultation?", description: "Yes. We begin with a conversation about your goals, site or audience, timeline, and budget so we can recommend the most useful next step." },
            { id: "contact-faq-3", title: "Can more than one division work on my project?", description: "Yes. Our construction, media, and solar teams can work independently or coordinate on one project—for example, building a property, installing its energy system, and producing launch content." },
            { id: "contact-faq-4", title: "What solar technology services do you provide?", description: "Our solar division supports energy assessments, system design, residential and commercial solar panel installation, battery storage, performance monitoring, and maintenance." },
          ],
        },
      ],
    },
  ],
}
